package com.chinarewards.qqgbvpn.domain.event;

public enum DomainEvent {

	// -------- UI Related -------------
	USER_LOGGED_IN, //
	USER_ADDED_POS, USER_REMOVED_POS, //
	USER_ADDED_AGENT, USER_REMOVED_AGENT, //
	USER_ADDED_DNOTE, USER_ADDED_DNOTE_DTL, USER_REMOVED_DNOTE_DTL, USER_REMOVED_DNOTE, //
	USER_CONFIRMED_DNOTE, USER_PRINTED_DNOTE, //
	USER_ADDED_RNOTE, USER_ADDED_RNOTE_DTL,

	// ---------- POS Server Related -------------
	POS_INIT_REQ, POS_INIT_OK, POS_INIT_FAILED, POS_LOGGED_IN, //
	POS_PRODUCT_SEARCH, POS_ORDER_VALIDATED_OK, POS_ORDER_VALIDATED_FAILED
}
